Create guidlines for contributors
ise621/building-envelope-data pull request #159
Opened 2020-12-08 14:56 UTC by christoph-maurer

2020-12-09 11:39 UTC, christoph-maurer commented
@simon-wacker Do you think we should already use Github Discussions?

2020-12-09 12:11 UTC, simon-wacker commented
I have no experience with GitHub Discussions. It sounds like a good idea.

2020-12-09 18:13 UTC, simon-wacker requested changes

2020-12-09 18:13 UTC, simon-wacker commented on CONTRIBUTING.md
> +- [ ] Run `make shell` and `make format` to format branch with [Prettier](https://prettier.io).
You run `make shell` to drop into a shell within a fresh Docker container (this is only needed if you use Docker). You can then run `make format` to format the code. Formatting code is not a test --- it polishes the code and makes it adhere to our coding styles.

2020-12-09 18:13 UTC, simon-wacker commented on CONTRIBUTING.md
> +- [ ] Use `make example` and verify that all examples are valid against the schemas.
Wording should `Run` instead of `Use` and `to verify` instead of `and verify`. Same below and above.

2020-12-09 18:13 UTC, simon-wacker commented on README.md
> +In order to use all functions of this code for example to format and test, please follow the instructions below.
Rephrase to: `In order to use our development tooling, for example, to format code and to run tests, follow the instructions below.`

2020-12-10 08:42 UTC, christoph-maurer commented
@simon-wacker I addressed the three comments of your review with eb8af6bae3b3600b91442ebc8133ca46cd33dbd7.

2020-12-10 10:48 UTC, simon-wacker approved these changes

2020-12-10 13:40 UTC, merged